from virtual_bank.tests.tests_customer.test_customer_create import TestCustomerCreate
from virtual_bank.tests.tests_customer.test_customer_get import TestCustomerGet
from virtual_bank.tests.tests_customer.test_customer_post import TestCustomerPost
