# Generated by Django 4.0.6 on 2022-07-07 15:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('account_number', models.CharField(default='', max_length=8, primary_key=True, serialize=False)),
                ('balance', models.FloatField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='opening_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 7, 15, 33, 12, 180040, tzinfo=utc), verbose_name='Data de abertura'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 7, 7, 15, 33, 12, 182034, tzinfo=utc)),
        ),
    ]
