# Generated by Django 4.0.6 on 2022-07-09 13:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='opening_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 9, 13, 22, 25, 950013, tzinfo=utc), verbose_name='Data de abertura'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 7, 9, 13, 22, 25, 951010, tzinfo=utc)),
        ),
    ]
