# Generated by Django 4.0.6 on 2022-07-09 15:08

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_bank', '0002_alter_account_opening_date_alter_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='address',
            name='district',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='address',
            name='neighborhood',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='zip_number',
            field=models.IntegerField(default=0, unique=True, validators=[django.core.validators.MaxValueValidator(99999999)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='opening_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 9, 15, 7, 59, 227833, tzinfo=utc), verbose_name='Data de abertura'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 7, 9, 15, 7, 59, 311017, tzinfo=utc)),
        ),
    ]
