# Generated by Django 4.0.6 on 2022-07-09 16:17

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_bank', '0003_address_city_address_district_address_neighborhood_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='zip_number',
        ),
        migrations.AlterField(
            model_name='account',
            name='opening_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 9, 16, 17, 4, 216316, tzinfo=utc), verbose_name='Data de abertura'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(default='', max_length=80, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(default='', max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='address',
            name='neighborhood',
            field=models.CharField(default='', max_length=80, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(default='', max_length=100, verbose_name='Logradouro'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(help_text='Formato: 00.000-000', max_length=9, unique=True, validators=[django.core.validators.RegexValidator('[0-9]{5}-[0-9]{3}', message='Formato de CEP inválido')], verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='client_type',
            field=models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PF', max_length=2, verbose_name='Tipo de cliente'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='complement',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Complemento (endereço)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='door_number',
            field=models.CharField(default='', max_length=10, verbose_name='Número (endereço)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(default='', help_text='Formato: +DI DD 00000-0000', max_length=20, validators=[django.core.validators.RegexValidator('\\+[0-9]{2} [0-9]{2} (?:[2-8]|9[1-9])[0-9]{3}-[0-9]{4}', message='Telefone em formato inválido')], verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='zip_code',
            field=models.CharField(help_text='Formato: 00000-000', max_length=9, validators=[django.core.validators.RegexValidator('[0-9]{5}-[0-9]{3}')]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 7, 9, 16, 17, 4, 364185, tzinfo=utc)),
        ),
    ]
