# Generated by Django 4.0.5 on 2022-07-03 17:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PF', 'Física'), ('PJ', 'Jurídica')], default='PF', max_length=2)),
                ('cpf_cnpj', models.BigIntegerField(default=0, help_text='Somente números', unique=True, validators=[django.core.validators.MaxValueValidator(99999999999999)], verbose_name='CPF/CNPJ')),
                ('nome_razao_social', models.CharField(default='', max_length=80, verbose_name='Nome completo ou Razão social')),
                ('endereco', models.CharField(default='', max_length=100, verbose_name='Endereço completo')),
                ('telefone', models.CharField(default='', help_text=' +DI (DDD) 00000-0000', max_length=20, validators=[django.core.validators.RegexValidator('\\+[0-9]{2} \\(0[0-9]{2}\\) (?:[2-8]|9[1-9])[0-9]{3}-[0-9]{4}', message='Telefone em formato inválido')], verbose_name='Telefone')),
                ('email', models.CharField(default='', max_length=50, validators=[django.core.validators.EmailValidator()])),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('numero_conta', models.CharField(default='', max_length=6, unique=True, verbose_name='Número da Conta')),
                ('seed', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('digito_verificador', models.IntegerField(default=0, verbose_name='Dígito verificador da conta')),
                ('conta_ativa', models.BooleanField(default=True)),
                ('saldo', models.FloatField(default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco_digital.cliente')),
            ],
        ),
    ]
