# Generated by Django 4.0.5 on 2022-07-02 17:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PF', 'Física'), ('PJ', 'Jurídica')], default='PF', max_length=2)),
                ('cpf_cnpj', models.BigIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99999999999999)], verbose_name='CPF ou CNPJ')),
                ('nome_razao_social', models.CharField(default='', max_length=80, verbose_name='Nome completo ou Razão social')),
                ('endereco', models.CharField(default='', max_length=100, verbose_name='Endereço completo')),
                ('telefone', models.CharField(default='', max_length=15)),
                ('email', models.CharField(default='', max_length=50, validators=[django.core.validators.EmailValidator()])),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('numero_conta', models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(999999)], verbose_name='Número da Conta')),
                ('status', models.CharField(choices=[('AT', 'Ativa'), ('IN', 'Inativa')], default='AT', max_length=2)),
                ('saldo', models.FloatField(default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco_digital.cliente')),
            ],
        ),
    ]
