# Generated by Django 4.0.5 on 2022-07-02 21:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_digital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conta',
            name='status',
        ),
        migrations.AddField(
            model_name='conta',
            name='conta_ativa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='conta',
            name='digito_verificador',
            field=models.IntegerField(default=0, verbose_name='Dígito verificador da conta'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf_cnpj',
            field=models.BigIntegerField(default=0, unique=True, validators=[django.core.validators.MaxValueValidator(99999999999999)], verbose_name='CPF/CNPJ (somente números)'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(default='', max_length=20, verbose_name='Telefone\nFormatos aceitos:\n+DI (DDD) 0000-0000\n+DI (DDD) 00000-0000'),
        ),
        migrations.AlterField(
            model_name='conta',
            name='numero_conta',
            field=models.IntegerField(default=15457, primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(999999)], verbose_name='Número da Conta'),
        ),
    ]
