# Generated by Django 4.0.5 on 2022-07-03 22:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('banco_digital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='saldo',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='conta',
            name='data_abertura',
            field=models.DateField(default=datetime.datetime(2022, 7, 3, 22, 6, 22, 643998, tzinfo=utc), verbose_name='Data de abertura'),
        ),
    ]
