# Generated by Django 4.0.5 on 2022-07-05 00:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('banco_digital', '0002_conta_saldo_alter_conta_data_abertura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='data_abertura',
            field=models.DateField(default=datetime.datetime(2022, 7, 5, 0, 12, 49, 762718, tzinfo=utc), verbose_name='Data de abertura'),
        ),
    ]
