# Generated by Django 4.0.5 on 2022-07-02 23:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_digital', '0002_remove_conta_status_conta_conta_ativa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf_cnpj',
            field=models.CharField(default=0, max_length=14, unique=True, verbose_name='CPF/CNPJ (somente números)'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(default='', max_length=20, validators=[django.core.validators.RegexValidator('\\+[0-9]{2} \\(0[0-9]{2}\\) (?:[2-8]|9[1-9])[0-9]{3}-[0-9]{4}', message='Telefone em formato inválido')], verbose_name='Telefone: +DI (DDD) 00000-0000\n+DI'),
        ),
        migrations.AlterField(
            model_name='conta',
            name='numero_conta',
            field=models.CharField(default='608271', max_length=6, primary_key=True, serialize=False, verbose_name='Número da Conta'),
        ),
    ]
